POST http://localhost:3001/api/inventory
Content-Type: application/json

{
    "product_name": "candy",
    "sku": 11001,
    "location": "A11",
    "count": "13"
}
###
DELETE http://localhost:3001/api/inventory/0

###

GET http://localhost:3001/api/inventory/all

###

PUT http://localhost:3001/api/inventory/1
Content-Type: application/json

{
    "product_name": "cinnamon",
    "sku": 11001,
    "location": "A11",
    "count": "13"
}