POST http://localhost:3001/api/inventory/
Content-Type: application/json

{
    "product_name": "candy",
    "sku": "11001",
    "location": "A11",
    "count": "13"
}
###
DELETE http://localhost:3001/api/inventory/

###

GET http://localhost:3001/api/inventory/all

###
GET http://localhost:3001/api/inventory/

###

PUT http://localhost:3001/api/inventory/1
Content-Type: application/json

{
    "product_name": "Dried Chiles",
    "sku": "1100112",
    "location": "A7",
    "count": 26
}